name: devtools_visualizer
description: A DevTools extension for the Trigger package.
publish_to: 'none' # เพราะเราไม่ได้กะจะ publish ตัวนี้แยก
version: 1.0.0+1

environment:
  sdk: '>=3.10.8 <4.0.0' # หรือ version ที่คุณใช้อยู่

dependencies:
  flutter:
    sdk: flutter
  # พระเอกที่จะเชื่อมต่อกับ DevTools
  devtools_extensions: ^0.1.0 
  # ชี้กลับมาที่ package หลักของเรา
  trigger: 
    path: ../ 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true